FROM python:3.7.9-stretch

WORKDIR /myflask

RUN pip install flask
RUN pip install flask_restful
RUN pip install pymysql
RUN pip install kafka-python

COPY ./order_ms.py /myflask/app.py

CMD ["flask", "run", "--host", "0.0.0.0", "--port", "5000"]
