FROM python:3.7.9-stretch

WORKDIR /myflask

RUN pip install flask
RUN pip install flask_restful
RUN pip install pymysql

COPY ./delivery_ms.py /myflask/app.py

CMD ["flask", "run", "--host", "0.0.0.0", "--port", "6000"]
